Feature/tests
wearesho-team/yii2-google-autocomplete pull request #4
Opened 2018-10-02 13:09 UTC by KartaviK

2018-10-02 14:03 UTC, sashabeton approved these changes

2018-10-02 15:06 UTC, Horat1us requested changes

2018-10-02 15:06 UTC, Horat1us commented on tests/Unit/Panels/StreetsPanelTest.php
> +        $this->expectedRules = [
Rules should not be checked as array equal. Rules should be checked using validation.
So, you need to fill attribute and then run ->validate(['attributeName']) with some error/success expectation.

2018-10-03 07:05 UTC, Horat1us requested changes

2018-10-03 07:05 UTC, Horat1us commented on README.md
> +## Authors
Contributors section

2018-10-03 07:05 UTC, Horat1us commented on README.md
> +            'class' => \Wearesho\GoogleAutocomplete\Yii\Controller::class,
Example should have `use Wearesho\GoogleAutocomplete` in header.

2018-10-03 07:05 UTC, Horat1us commented on README.md
> +# Yii2 Google autocomplete api integrate
Missing `Installation` section

2018-10-03 07:06 UTC, Horat1us requested changes

2018-10-03 07:06 UTC, Horat1us commented on README.md
> +# Yii2 Google autocomplete api integrate
Titles have to be first-character uppercased in english

2018-10-03 07:45 UTC, merged